# Generated by Django 5.1.11 on 2025-09-02 11:25

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to=main.models.about_upload)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🖼 About Image',
                'verbose_name_plural': '🖼 About Images',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_handled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '📩 Contact Message',
                'verbose_name_plural': '📩 Contact Messages',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='DepartmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=main.models.settings_upload)),
                ('about_short', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('x_twitter', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '⚙️ Department Setting',
                'verbose_name_plural': '⚙️ Department Settings',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('Workshop', 'Workshop'), ('Seminar', 'Seminar'), ('Symposium', 'Symposium'), ('Competition', 'Competition'), ('Guest Lecture', 'Guest Lecture'), ('Other', 'Other')], default='Other', max_length=32)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.events_upload)),
                ('is_registration_open', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🎉 Event',
                'verbose_name_plural': '🎉 Events',
                'ordering': ('-start_at',),
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course', models.CharField(help_text='e.g., B.Sc CS / BCA / M.Sc CS', max_length=120)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('exam_date', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=main.models.exams_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '📋 Exam',
                'verbose_name_plural': '📋 Exams',
                'ordering': ('exam_date', 'semester'),
            },
        ),
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], default='photo', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.photos_upload)),
                ('video', models.FileField(blank=True, null=True, upload_to='gallery/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, choices=[(2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000)], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '📸 Gallery Media',
                'verbose_name_plural': '📸 Gallery Media',
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('category', models.CharField(choices=[('Announcement', 'Announcement'), ('Achievement', 'Achievement'), ('Placement', 'Placement'), ('Research', 'Research'), ('Notice', 'Notice'), ('General', 'General')], default='General', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.news_upload)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '📰 News',
                'verbose_name_plural': '📰 News',
                'ordering': ('-published_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.slider_upload)),
                ('video', models.FileField(blank=True, null=True, upload_to=main.models.slider_video_upload)),
                ('caption', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🎞️ Slider',
                'verbose_name_plural': '🎞️ Sliders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('HOD', 'HOD'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lab Instructor', 'Lab Instructor'), ('Technical Staff', 'Technical Staff'), ('Support', 'Support')], default='Assistant Professor', max_length=32)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('qualifications', models.CharField(blank=True, max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, help_text='Area of interest / expertise', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('profile_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=main.models.staff_upload)),
                ('is_hod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '👩\u200d🏫 Staff Profile',
                'verbose_name_plural': '👨\u200d🏫 Staff Profiles',
                'ordering': ('role', 'name'),
            },
        ),
    ]
