# Generated by Django 5.1.12 on 2025-09-10 11:52

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to=main.models.highlight_upload)),
                ('link', models.URLField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '✨ Highlight Card',
                'verbose_name_plural': '✨ Highlight Cards',
                'ordering': ('order', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key for section (e.g. 'bottom', 'about')", max_length=50)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to=main.models.section_upload)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🖼 Section Image',
                'verbose_name_plural': '🖼 Section Images',
                'ordering': ('-created_at',),
            },
        ),
    ]
