# Generated by Django 5.1.12 on 2025-09-10 13:58

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_highlightcard_sectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=main.models.photos_upload)),
                ('year', models.PositiveIntegerField(blank=True, choices=[(2025, 2025), (2024, 2024), (2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000)], null=True)),
                ('category', models.CharField(blank=True, choices=[('event', 'Event'), ('workshop', 'Workshop'), ('annual', 'Annual'), ('misc', 'Miscellaneous')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🗂️ Album',
                'verbose_name_plural': '🗂️ Albums',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='gallerymedia',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='main.album'),
        ),
    ]
