# Generated by Django 5.1.12 on 2025-09-10 16:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_album_gallerymedia_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text='e.g., B.Sc CS / BCA / M.Sc CS', max_length=120)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=main.models.timetable_upload)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '📅 Class Timetable',
                'verbose_name_plural': '📅 Class Timetables',
                'ordering': ('-created_at', 'course', 'semester'),
            },
        ),
    ]
