# Generated by Django 5.1.12 on 2025-09-11 17:09

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_classtimetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, help_text='Self-hosted video file (MP4/WebM).', null=True, upload_to=main.models.events_upload),
        ),
        migrations.AddField(
            model_name='event',
            name='video_captions',
            field=models.FileField(blank=True, help_text='Optional VTT captions file.', null=True, upload_to=main.models.events_upload),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='External video URL (YouTube / Vimeo).', null=True),
        ),
    ]
