# Generated by Django 5.1.12 on 2025-09-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_event_video_event_video_captions_event_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ('-is_hod', 'order', 'role', 'name'), 'verbose_name': '👩\u200d🏫 Staff Profile', 'verbose_name_plural': '👨\u200d🏫 Staff Profiles'},
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Manual ordering priority (lower appears earlier)'),
        ),
    ]
